campus/urls.py
from django.urls import path
from campus import views
from .views import TopUniversitiesView #Xuanming Feng


app_name = 'universities'

urlpatterns = [
    path('', views.university_list, name='university_list'),
    path('university_detail/<slug:university_name_slug>/', views.university_detail, name='university_detail'),
    path('courses/<slug:course_name_slug>/', views.course_detail, name='course_detail'),
    path('courses/<slug:course_name_slug>/submit_review/', views.submit_review, name='submit_review'),
    path('top_universities/', views.TopUniversitiesView.as_view(), name='top_universities'),
    path('courses/<slug:course_name_slug>/contacting/', views.contacting, name='contacting'),
    path('courses/<slug:course_name_slug>/tip/', views.tip, name='tip'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),

]

campus_check_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from campus import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('universities/', include('campus.urls')),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('map/', views.map, name='map'),
        
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Avg
from django.template.defaultfilters import slugify

class Location(models.Model):
    name = models.CharField(max_length=100)
    longitude = models.FloatField()
    latitude = models.FloatField()
    university_slug = models.SlugField(unique=True, null=True)

    def __str__(self):
        return f'{self.name}'
    class Meta:
        verbose_name_plural = 'Locations'

class Degree(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'Degrees'

class University(models.Model):
    name = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    degree = models.ManyToManyField(Degree, related_name='universities')
    logo = models.ImageField(upload_to='university_logos')
    description = models.TextField()
    website = models.URLField()
    contact_email = models.EmailField()
    slug = models.SlugField(unique=True)

    @property
    def avg_rating(self):
        course_reviews = Review.objects.filter(course__university=self)
        if course_reviews.exists():
            value_for_money_avg = course_reviews.aggregate(Avg('value_for_money'))['value_for_money__avg']
            teaching_quality_avg = course_reviews.aggregate(Avg('teaching_quality'))['teaching_quality__avg']
            course_content_avg = course_reviews.aggregate(Avg('course_content'))['course_content__avg']
            job_prospects_avg = course_reviews.aggregate(Avg('job_prospects'))['job_prospects__avg']
            return (value_for_money_avg + teaching_quality_avg + course_content_avg + job_prospects_avg) / 4
        else:
            return None
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(University, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'Universities'

class Course(models.Model):
    name = models.CharField(max_length=100)
    course_code = models.CharField(max_length=10)
    description = models.TextField()
    university = models.ForeignKey(University, on_delete=models.CASCADE, related_name='courses')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Course, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.course_code}: {self.name}"
    class Meta:
        verbose_name_plural = 'Courses'


class Enrollment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    university = models.ForeignKey('University', on_delete=models.CASCADE)
    degree = models.ForeignKey('Degree', on_delete=models.CASCADE)
    courses = models.ManyToManyField('Course', related_name='enrollments')
    enrollment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.university} ({self.degree})'

    class Meta:
        verbose_name_plural = 'Enrollments'

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    university = models.ForeignKey('University', on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    value_for_money = models.IntegerField()
    teaching_quality = models.IntegerField()
    course_content = models.IntegerField()
    job_prospects = models.IntegerField()
    review_text = models.TextField()
    review_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.university} ({self.course})'
    
    class Meta:
        verbose_name_plural = 'Reviews'


class StudentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.username}\'s profile'

    class Meta:
        verbose_name_plural = 'StudentProfiles'

campus/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import University, Course, Location, Review, Enrollment, StudentProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse
from .forms import ReviewForm, StudentProfileForm, StudentRegistrationForm
from django.db.models import Avg, Sum, Q
import json
from django.contrib import messages
from django.views.generic import ListView #XuanmingFeng
from django.http import JsonResponse


def search_suggestions(request):
    #search term is extracted from the GET parameters of the request
    search_term = request.GET.get('term', '')
    #universities, courses, and cities that match the search term are queried
    universities = University.objects.filter(Q(name__icontains=search_term) | 
                                              Q(location__name__icontains=search_term))
    courses = Course.objects.filter(name__icontains=search_term)
    cities = University.objects.filter(location__name__icontains=search_term).values_list('location__name', flat=True)
    suggestions = {
        'universities': list(universities.values_list('name', flat=True)),
        'courses': list(courses.values_list('name', flat=True)),
        'cities': list(set(cities)),
    }
    return JsonResponse(suggestions)

@login_required
def student_profile(request):
    try:
        profile = StudentProfile.objects.get(user=request.user)
    except StudentProfile.DoesNotExist:
        profile = StudentProfile(user=request.user)
        profile.save()

    # Get the Enrollment object for the current user
    enrollment = Enrollment.objects.filter(user=request.user).first()

    # Get the courses related to the Enrollment object, if it exists
    if enrollment:
        courses = enrollment.courses.all()
    else:
        courses = Course.objects.none()

    reviews = Review.objects.filter(user=request.user)
    ratings_by_course = {}

    for review in reviews:
        if review.course_id not in ratings_by_course:
            ratings_by_course[review.course_id] = {
                'value_for_money': [review.value_for_money],
                'teaching_quality': [review.teaching_quality],
                'course_content': [review.course_content],
                'job_prospects': [review.job_prospects],
                'review_text': [review.review_text],
            }
        else:
            ratings_by_course[review.course_id]['value_for_money'].append(review.value_for_money)
            ratings_by_course[review.course_id]['teaching_quality'].append(review.teaching_quality)
            ratings_by_course[review.course_id]['course_content'].append(review.course_content)
            ratings_by_course[review.course_id]['job_prospects'].append(review.job_prospects)
            ratings_by_course[review.course_id]['review_text'].append(review.review_text)

    for course in courses:
        if course.id in ratings_by_course:
            course.avg_rating = sum(ratings_by_course[course.id]['value_for_money'][:3]) / (4 * len(ratings_by_course[course.id]['value_for_money'][:3]))
            course.review_text = ratings_by_course[course.id]['review_text'][0]
        else:
            course.avg_rating = None
            course.review_text = None

    form = StudentProfileForm(instance=profile)

    if request.method == 'POST':
        form = StudentProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your information has been updated successfully.')
            return redirect(reverse('student_profile'))

    context = {
        'form': form,
        'courses': courses
    }

    return render(request, 'campus/student_profile.html', context)


@login_required
def submit_review(request, course_name_slug):
    course = get_object_or_404(Course, slug=course_name_slug)
    if request.method == 'POST':
        form = ReviewForm(request.POST, user=request.user, course=course)
        if form.is_valid():
            enrollment = Enrollment.objects.filter(user=request.user, courses=course).first()
            #Check if the user has enrolled in the course, if not, return an error message and redirect the user to the course_detail page.
            if not enrollment:
                messages.error(request, "You cannot review a course that you have not enrolled in.")
                return redirect('universities:course_detail', course_name_slug=course_name_slug)
            #Check if the user has already submitted a review for this course, if yes, return an error message and redirect the user to the course_detail page
            if Review.objects.filter(user=request.user, course=course).exists():
                messages.error(request, "You have already submitted a review for this course.")
                return redirect('universities:course_detail', course_name_slug=course_name_slug)
            review = form.save(commit=False)
            review.user = request.user
            review.course = course
            review.university = course.university
            review.save()
            messages.success(request, 'Your review has been submitted successfully!')
            return redirect('universities:course_detail', course_name_slug=course_name_slug)
    else:
        form = ReviewForm(user=request.user, course=course)
    return render(request, 'campus/submit_review.html', {'form': form, 'course': course})


def register(request):
    if request.method == 'POST':
        form = StudentRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('login')
    else:
        form = StudentRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('universities:university_list')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

def index(request):
    return render(request, 'campus/index.html')


def university_list(request):
    universities = University.objects.all()
    search_term = request.GET.get('search', '')
    # Filter universities based on search term 
    if search_term:
        universities = universities.filter(Q(name__icontains=search_term) | 
                                           Q(location__name__icontains=search_term) | 
                                           Q(degree__name__icontains=search_term) | 
                                           Q(courses__name__icontains=search_term))

    university_ratings = {}
    # Loop through universities, prefetch courses and reviews, and calculate ratings
    for university in universities.select_related('location').prefetch_related('courses__review_set'):
        course_ratings = []
        courses = university.courses.all()
         # Loop through courses and calculate ratings
        for course in courses:
            reviews = course.review_set.all()
            # Calculate the course rating as the average of the four review criteria
            if reviews:
                course_rating = (reviews.aggregate(
                    Avg('value_for_money'))['value_for_money__avg'] +
                                 reviews.aggregate(
                    Avg('teaching_quality'))['teaching_quality__avg'] +
                                 reviews.aggregate(
                    Avg('course_content'))['course_content__avg'] +
                                 reviews.aggregate(
                    Avg('job_prospects'))['job_prospects__avg']) / 4
                course_ratings.append(course_rating)
        if course_ratings:
            # Calculate the university rating as the average of all course ratings
            university_rating = sum(course_ratings) / len(course_ratings)
        else:
            university_rating = 0
        university_ratings[university] = university_rating

    context = {
        'university_ratings': university_ratings,
    }
    return render(request, 'campus/university_list.html', context)


def university_detail(request, university_name_slug):
    # Retrieve the University object with the matching slug, or return a 404 error if it doesn't exist.
    university = get_object_or_404(University, slug=university_name_slug)
    # Retrieve all courses that are associated with the university.
    courses = Course.objects.filter(university=university)
    course_ratings = []
    # Iterate through each course to retrieve the associated reviews and calculate the course rating
    for course in courses:
        reviews = course.review_set.all()
        if reviews:
            course_rating = (reviews.aggregate(
                Avg('value_for_money'))['value_for_money__avg'] +
                                 reviews.aggregate(
                    Avg('teaching_quality'))['teaching_quality__avg'] +
                                 reviews.aggregate(
                    Avg('course_content'))['course_content__avg'] +
                                 reviews.aggregate(
                    Avg('job_prospects'))['job_prospects__avg']) / 4
            course_ratings.append(course_rating)
    # Calculate the university rating by averaging the course ratings, if there are any
    if course_ratings:
        university_rating = sum(course_ratings) / len(course_ratings)
    else:
        university_rating = 0

templates/campus/Contacting.html
{% extends 'campus/base.html' %}
{% block content %}
  <h2>Your contact details</h2>
    <form action="{% url 'universities:tip' course.slug %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Input your name" class="input-item" required="required"><br/><br/>
    <input type="email" name="email" placeholder="Input your email" class="input-item" required="required"><br/><br/>
    <input class="btn btn-primary btn-lg beautiful-button" type="submit" value="Send"/>
    </form>
{% endblock %}

templates/campus/Map.html
{% extends 'campus/base.html' %}
{% load static %}
<title>Map</title>
{% block content %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
            integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
            crossorigin=""></script>
    <script src="{% static 'js/map.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}"/>

    <!--Map-->
    <div id="map" data-locations="{{ locations }}"></div>

{% endblock %}

templates/campus/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CampusCheck</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
</head>
<body>
    <!-- Top header with site logo and navigation links -->
   <nav class="navbar navbar-expand-lg navbar-light bg-brown custom-header container my-4 bg-image">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'image/logo.png' %}" alt="CampusCheck Logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'universities:university_list' %}">Universities</a>   
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'universities:top_universities' %}">Top-5 Universities</a>   
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'map' %}">Map</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>   
                </li>
                </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student_profile' %}">My Profile</a>
                    </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>   
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
    <div class="container my-4">
        <!-- Main content of the page -->
        {% block content %}
        {% endblock %}
    </div>

<!-- jQuery UI Autocomplete -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
<!-- Bootstrap JS and jQuery -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/campus/course_detail.html
{% extends 'campus/base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
    <h1 class="display-4">{{ course.name }}</h1>
    <div class="row">
      <div class="col-md-8">
        <p class="lead">{{ course.description }}</p>
        <p>Offered by: {{ course.university.name }}</p>
        <p>Website: <a href="{{ course.university.website }}">{{ course.university.website }}</a></p>
        <p>Contact email: {{ course.university.contact_email }}</p>
        <p>Average Rating:
          <span class="fa fa-star {% if rating > 0 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if rating > 1 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if rating > 2 %} checked {% endif %}"></span>
          <span class="fa fa-star {% if rating > 3 %} checked {% endif %}" ></span>
          <span class="fa fa-star {% if rating > 4 %} checked {% endif %}"></span>
        </p>
        {% if request.user.is_authenticated %}
          <a href="{% url 'universities:submit_review' course.slug %}" class="btn btn-primary beautiful-button">Submit a review</a>
        {% else %}
          <p><a href="{% url 'login' %}">Login to submit a review</a></p>
        {% endif %}
      </div>
    </div>
    {% if reviews %}
      <h2 class="mt-5">Reviews</h2>
      <ul class="list-unstyled">
        {% for review in reviews %}
          <li class="mb-4">
            <div class="media">
              <div>
                <img src="{% static 'image/default.png' %}" alt="Profile Picture" class="img-thumbnail rounded-circle" width="50" height="50">
              </div>
              <div class="media-body ml-3">
                <p>{{ review.review_text }}</p>
                <p class="text-muted mb-0">Submitted by: {{ review.user.username }}</p>
                <p class="text-muted mb-0">Average Rating:
                  <span class="fa fa-star {% if review.value_for_money > 0 %} checked {% endif %}"></span>
                  <span class="fa fa-star {% if review.value_for_money > 1 %} checked {% endif %}"></span>
                  <span class="fa fa-star {% if review.value_for_money > 2 %} checked {% endif %}"></span>
                  <span class="fa fa-star {% if review.value_for_money > 3 %} checked {% endif %}" ></span>
                  <span class="fa fa-star {% if review.value_for_money > 4 %} checked {% endif %}"></span>
                </p>
                <br>
                <a class="btn btn-primary beautiful-button" href="{% url 'universities:contacting' course.slug %}" role="button">Get in touch</a>
              </div>
            </div>
            <hr>
          </li>
        {% empty %}
          <p>No reviews available for this course.</p>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

templates/campus/submit_review.html
{% extends 'campus/base.html' %}
{% load static %}
{% block content %}
{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}
<link rel="stylesheet" type="text/css" href="{% static 'css/stars_review.css' %}"/>
<h1> Submit your review here</h1>
<form method="post">
  {% csrf_token %}
 <div>
  <label for="id_value_for_money">Value for Money:</label>
  <div class="star-rating">
    <i class="my-star star-value-for-money star-1" data-star="1"></i>
    <i class="my-star star-value-for-money star-2" data-star="2"></i>
    <i class="my-star star-value-for-money star-3" data-star="3"></i>
    <i class="my-star star-value-for-money star-4" data-star="4"></i>
    <i class="my-star star-value-for-money star-5" data-star="5"></i>
  </div>
  <input type="hidden" name="value_for_money" id="id_value_for_money" value="">
</div>

<div>
  <label for="id_teaching_quality">Teaching Quality:</label>
  <div class="star-rating">
    <i class="my-star star-teaching-quality star-1" data-star="1"></i>
    <i class="my-star star-teaching-quality star-2" data-star="2"></i>
    <i class="my-star star-teaching-quality star-3" data-star="3"></i>
    <i class="my-star star-teaching-quality star-4" data-star="4"></i>
    <i class="my-star star-teaching-quality star-5" data-star="5"></i>
  </div>
  <input type="hidden" name="teaching_quality" id="id_teaching_quality" value="">
</div>
<div>
  <label for="id_course_content">Course Content:</label>
  <div class="star-rating">
    <i class="my-star star-course-content star-1" data-star="1"></i>
    <i class="my-star star-course-content star-2" data-star="2"></i>
    <i class="my-star star-course-content star-3" data-star="3"></i>
    <i class="my-star star-course-content star-4" data-star="4"></i>
    <i class="my-star star-course-content star-5" data-star="5"></i>
  </div>
  <input type="hidden" name="course_content" id="id_course_content" value="">
</div>
<div>
  <label for="id_job_prospects">Job Prospects:</label>
  <div class="star-rating">
    <i class="my-star star-job-prospects star-1" data-star="1"></i>
    <i class="my-star star-job-prospects star-2" data-star="2"></i>
    <i class="my-star star-job-prospects star-3" data-star="3"></i>
    <i class="my-star star-job-prospects star-4" data-star="4"></i>
    <i class="my-star star-job-prospects star-5" data-star="5"></i>
  </div>
  <input type="hidden" name="job_prospects" id="id_job_prospects" value="">
</div>
  <div>
    <label for="id_review_text">Review Text:</label>
    <p>
    <textarea name="review_text" id="id_review_text"></textarea></p>
  </div>
  <button class="btn btn-primary beautiful-button" type="submit" >Submit Review</button>
</form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.13.1/jquery-ui.js"></script> 
<script src="{% static 'js/stars_review.js' %}" type="text/javascript"></script>
{% endblock %}

templates/campus/top_universities.html
{% extends 'campus/base.html' %}
{% block content %} 
<h2>Top Universities</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Location</th>
      <th>Average Rating</th>
    </tr>
  </thead>
  <tbody> {% if top_universities %} 
  <div class="row justify-content-center">
  <div class="col-md-6 mb-4">
      <div class="card">
        <img src="{{ top_universities.0.0.logo.url }}" alt="{{ top_universities.0.0.name }} logo" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">
            #1 👑<a href="{% url 'universities:university_detail' top_universities.0.0.slug %}"> {{ top_universities.0.0.name }}</a> 
          </h5>
          <p class="card-text">Location: {{ top_universities.0.0.location }}</p>
          </p> {% if top_universities.0.1 is not None %} <p class="card-text">Rating: 
            <span class="fa fa-star {% if top_universities.0.1 > 0 %} checked {% endif %}"></span>
            <span class="fa fa-star {% if top_universities.0.1 > 1 %} checked {% endif %}"></span>
            <span class="fa fa-star {% if top_universities.0.1 > 2 %} checked {% endif %}"></span>
            <span class="fa fa-star {% if top_universities.0.1 > 3 %} checked {% endif %}"></span>
            <span class="fa fa-star {% if top_universities.0.1 > 4 %} checked {% endif %}"></span>
          </p> {% endif %}
        </div>
      </div>
    </div> {% endif %} {% for top_university, rating in top_universities|slice:"1:" %} <tr>
      <td>{{ forloop.counter0|add:2}}</td>
      <td>
        <a href="{% url 'universities:university_detail' top_university.slug %}">{{ top_university.name }}</a>
      </td>
      <td>{{ top_university.location }}</td>
      <td>
        <span class="fa fa-star {% if rating > 0 %} checked {% endif %}"></span>
        <span class="fa fa-star {% if rating > 1 %} checked {% endif %}"></span>
        <span class="fa fa-star {% if rating > 2 %} checked {% endif %}"></span>
        <span class="fa fa-star {% if rating > 3 %} checked {% endif %}"></span>
        <span class="fa fa-star {% if rating > 4 %} checked {% endif %}"></span>
      </td>
    </tr> {% empty %} <tr>
      <td colspan="3">No universities found.</td>
    </tr> {% endfor %} </tbody>
</table> {% endblock %}

templates/campus/university_list.html
{% extends 'campus/base.html' %}
{% load static %}
{% block content %}
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- jQuery UI Autocomplete -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
<script src="{% static 'js/suggest.js' %}" type="text/javascript"></script>
<h1 class="mb-4">Universities</h1>

<form method="get" id="search-form">
    <span class="form-group">
        <label for="search">Search:</label>
        <input type="text" name="search" id="search" class="form-control" autocomplete="off" value="{{ request.GET.search }}" data-url="{% url 'universities:search_suggestions' %}">
        <button type="submit" class="btn btn-primary mb-1 beautiful-button">Search</button>
    </span>
</form>
<div class="row" id="university-list">
    {% for university, rating in university_ratings.items %}
        <div class="col-md-6 mb-4 ">
            <div class="card">
                <img src="{{ university.logo.url }}" alt="{{ university.name }} logo" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'universities:university_detail' university.slug %}">{{ university.name }}</a></h5>
                    <p class="card-text">{{ university.description }}</p>
                    <p class="card-text">Location: {{ university.location }}</p>
                    <p class="card-text">Website: <a href="{{ university.website }}">{{ university.website }}</a></p>
                    {% if rating %}
                        <p class="card-text">Rating:
                            <span class="fa fa-star {% if rating > 0 %} checked {% endif %}"></span>
                            <span class="fa fa-star {% if rating > 1 %} checked {% endif %}"></span>
                            <span class="fa fa-star {% if rating > 2 %} checked {% endif %}"></span>
                            <span class="fa fa-star {% if rating > 3 %} checked {% endif %}" ></span>
                            <span class="fa fa-star {% if rating > 4 %} checked {% endif %}"></span>
                        </p>
                    {% else %}
                        <p class="card-text">No ratings yet.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% empty %}
        <p>No universities available.</p>
    {% endfor %}
</div>
{% endblock %}